#!/usr/bin/env node
/**
 * Generate the advisory role prompts from the ai-context role charters.
 *
 * One source: every sentence a role is told comes from the charters (and, for
 * phase leads, the phase exit criteria in the SDLC contracts). This script only
 * selects and frames sections, so a charter change is a regenerate, never a
 * hand edit. `check` fails when the committed prompts no longer match.
 *
 * Sources are read with `git show <ref>:<path>` from an ai-context clone, so
 * the shared checkout's working tree and branch never matter.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const CONTRACTS = "reference/taxonomy-topology/ai-sdlc-contracts.md";
const PROMPTS = "roles/prompts";
const TEMPLATE = "checkpoint-template.md";

type Advisory = {
  catalogue: string;
  roles: Record<
    string,
    { charter_id: string; kind: "phase" | "domain"; section: string }
  >;
};
type Catalogue = { charter: string; roles: Record<string, { title: string }> };
export type Source = { path: string; blob: string; text: string };
export type Sources = { charter: Source; contracts: Source; ref: string };

function fail(message: string): never {
  throw new Error(message);
}

/** `## Heading` → body, in document order. Duplicate headings are refused. */
export function sections(markdown: string): Map<string, string> {
  const out = new Map<string, string>();
  const parts = markdown.split(/^## /m).slice(1);
  for (const part of parts) {
    const newline = part.indexOf("\n");
    const heading = part.slice(0, newline).trim();
    if (out.has(heading)) fail(`duplicate charter section: ${heading}`);
    out.set(heading, part.slice(newline + 1).trim());
  }
  return out;
}

function section(all: Map<string, string>, prefix: string): string {
  const matches = [...all.keys()].filter((k) => k.startsWith(prefix));
  if (matches.length !== 1)
    fail(
      `expected one charter section starting "${prefix}", found ${matches.length}`,
    );
  return all.get(matches[0])!;
}

function rows(body: string): string[][] {
  return body
    .split("\n")
    .filter((line) => line.startsWith("|"))
    .slice(2)
    .map((line) =>
      line
        .slice(1, -1)
        .split("|")
        .map((cell) => cell.trim()),
    );
}

function rowFor(body: string, charterId: string): string[] {
  const found = rows(body).filter((cells) =>
    cells[0].includes(`\`${charterId}\``),
  );
  if (found.length !== 1)
    fail(`expected one charter row for ${charterId}, found ${found.length}`);
  return found[0];
}

function codeBlock(body: string): string {
  const match = /```text\n([\s\S]*?)```/.exec(body);
  return match ? match[1] : fail("charter template has no ```text block");
}

/** The paragraphs of a section that are not tables. */
function prose(body: string): string[] {
  return body
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p && !p.startsWith("|"));
}

function stamp(sources: Sources, used: Source[]): string {
  const from = used.map((s) => `${s.path}@${s.blob.slice(0, 12)}`).join(", ");
  return (
    `<!-- Generated by scripts/roe-advisory-prompts.ts from ai-context ` +
    `${sources.ref}: ${from}. Do not edit; regenerate. -->`
  );
}

export function renderTemplate(sources: Sources): string {
  const charter = sections(sources.charter.text);
  return (
    `${stamp(sources, [sources.charter])}\n` +
    codeBlock(section(charter, "Checkpoint template"))
  );
}

export function renderRole(
  id: string,
  title: string,
  role: Advisory["roles"][string],
  sources: Sources,
): string {
  const charter = sections(sources.charter.text);
  const out: string[] = [];
  const used = [sources.charter];
  out.push(`# ${title} (\`${id}\`, charter \`${role.charter_id}\`)`);
  out.push(
    "You are an advisory role session in the Rock of Eye AI pilot. Everything " +
      "below is taken from the role charters; where this prompt and the current " +
      "charter disagree, the charter wins and the prompt needs regenerating.",
  );

  const roleBody = section(charter, role.section);
  const cells = rowFor(roleBody, role.charter_id);
  out.push("## Your role");
  const facts: string[] = [];
  const extra: string[] = [];
  if (role.kind === "phase") {
    facts.push(`- Phase: ${cells[0]}`);
    facts.push(`- Purpose and primary output: ${cells[1]}`);
    facts.push(`- Consult when material: ${cells[2]}`);
    const phase = cells[0].split(" /")[0].trim();
    const exits = rows(
      section(sections(sources.contracts.text), "Phase exit criteria"),
    ).filter((r) => r[0] === phase);
    if (exits.length !== 1)
      fail(`expected one phase exit row for ${phase}, found ${exits.length}`);
    facts.push(`- Exit question: ${exits[0][1]}`);
    facts.push(`- Proposed exit evidence: ${exits[0][2]}`);
    used.push(sources.contracts);
  } else {
    facts.push(`- Domain: ${cells[0]}`);
    facts.push(`- Responsibility: ${cells[1]}`);
    facts.push(`- Typical consultation result: ${cells[2]}`);
    for (const paragraph of prose(roleBody).slice(1)) {
      const subtopics = paragraph.startsWith("Security subtopics");
      if (!subtopics || role.charter_id === "dom-security")
        extra.push(paragraph);
    }
  }
  out.push(facts.join("\n"), ...extra);

  out.push("## Authority and working files");
  out.push(section(charter, "Activation"));
  out.push(
    `Your checkpoint is \`~/.ai/roles/${id}/checkpoint.md\`. Write each consultation result to \`~/.ai/roles/${id}/results/<request-id>.md\`.`,
  );
  out.push("## Shared charter");
  out.push(section(charter, "Shared charter"));
  out.push("## Initiative coordination");
  out.push(section(charter, "Initiative coordination"));
  for (const heading of [
    "Consultation request template",
    "Consultation result template",
    "Checkpoint template",
  ]) {
    out.push(`## ${heading}`);
    out.push(section(charter, heading));
  }
  return `${stamp(sources, used)}\n\n${out.join("\n\n")}\n`;
}

/** Every generated file, keyed by its path under roles/prompts/. */
export function renderAll(repo: string, sources: Sources): Map<string, string> {
  const advisory = JSON.parse(
    readFileSync(join(repo, "roles/advisory.json"), "utf8"),
  ) as Advisory;
  const catalogue = JSON.parse(
    readFileSync(join(repo, advisory.catalogue), "utf8"),
  ) as Catalogue;
  if (sources.charter.path !== catalogue.charter)
    fail(
      `catalogue names charter ${catalogue.charter}, not ${sources.charter.path}`,
    );
  const files = new Map<string, string>([[TEMPLATE, renderTemplate(sources)]]);
  for (const [id, role] of Object.entries(advisory.roles)) {
    const title =
      catalogue.roles[id]?.title ?? fail(`${id} is not in the catalogue`);
    files.set(`${id}.md`, renderRole(id, title, role, sources));
  }
  return files;
}

function git(root: string, args: string[]): string {
  const run = spawnSync("git", ["-C", root, ...args], { encoding: "utf8" });
  if (run.status !== 0) fail(`git ${args.join(" ")}: ${run.stderr.trim()}`);
  return run.stdout;
}

export function readSources(
  root: string,
  ref: string,
  charterPath: string,
): Sources {
  const read = (path: string): Source => ({
    path,
    blob: git(root, ["rev-parse", `${ref}:${path}`]).trim(),
    text: git(root, ["show", `${ref}:${path}`]),
  });
  return { ref, charter: read(charterPath), contracts: read(CONTRACTS) };
}

/** Writes (generate) or compares (check) the prompts; returns drifted paths. */
export function sync(
  repo: string,
  files: Map<string, string>,
  write: boolean,
): string[] {
  const drift: string[] = [];
  for (const [name, text] of files) {
    const path = join(repo, PROMPTS, name);
    if (existsSync(path) && readFileSync(path, "utf8") === text) continue;
    drift.push(join(PROMPTS, name));
    if (write) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, text);
    }
  }
  return drift;
}

const USAGE =
  "usage: roe-advisory-prompts generate|check [--ai-context DIR] [--ref REF]";

function main(args: string[]): number {
  const [action, ...rest] = args;
  const options: Record<string, string> = {
    "--ai-context": "/workspace/ai-context",
    "--ref": "origin/main",
  };
  for (let i = 0; i < rest.length; i += 2) {
    if (!(rest[i] in options) || !rest[i + 1]) fail(USAGE);
    options[rest[i]] = rest[i + 1];
  }
  if (action !== "generate" && action !== "check") fail(USAGE);
  const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const catalogue = JSON.parse(
    readFileSync(join(repo, "roles/catalogue.json"), "utf8"),
  ) as Catalogue;
  const sources = readSources(
    options["--ai-context"],
    options["--ref"],
    catalogue.charter,
  );
  const drift = sync(repo, renderAll(repo, sources), action === "generate");
  for (const path of drift)
    process.stdout.write(
      `${action === "generate" ? "wrote" : "stale"}: ${path}\n`,
    );
  if (action === "check" && drift.length) {
    process.stdout.write(
      "prompts are stale; run roe-advisory-prompts generate\n",
    );
    return 1;
  }
  if (!drift.length) process.stdout.write("prompts match the charter\n");
  return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(
      `roe-advisory-prompts: ${error instanceof Error ? error.message : String(error)}\n`,
    );
    process.exitCode = 1;
  }
}
