#!/usr/bin/env bash
# dotai — setup script
# Wires context docs and slash commands into Claude Code (and optionally Cursor/Windsurf).
# Run this once after cloning a repo, or let the devcontainer's postCreateCommand invoke it.

set -euo pipefail

# ── Resolve paths ────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVEX_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="${PWD}"

echo ""
echo "dotai — Setup"
echo "=============="
echo "dotai dir  : $DEVEX_DIR"
echo "Target repo: $REPO_DIR"
echo ""

# ── Claude Code ───────────────────────────────────────────────────────────────

CLAUDE_DIR="$HOME/.claude"
CLAUDE_COMMANDS_DIR="$CLAUDE_DIR/commands"

mkdir -p "$CLAUDE_COMMANDS_DIR"

echo ""
echo "→ Linking slash commands into ~/.claude/commands/"
# Commands are invoked as /command-name in a Claude Code session
# We symlink so updates to this repo are reflected immediately
for f in "$DEVEX_DIR/commands/"*.md; do
  name="$(basename "$f")"
  ln -sf "$f" "$CLAUDE_COMMANDS_DIR/$name"
  echo "  ✓ /$(basename "$name" .md)"
done

# ── Claude Code skills ───────────────────────────────────────────────────────
# Symlink each skill dir (one containing a SKILL.md) into ~/.claude/skills/ so
# updates here are picked up immediately. Personal collection — applies
# everywhere this user runs Claude Code.

CLAUDE_SKILLS_DIR="$CLAUDE_DIR/skills"
mkdir -p "$CLAUDE_SKILLS_DIR"

echo ""
echo "→ Linking skills into ~/.claude/skills/"
for d in "$DEVEX_DIR/skills/"*/; do
  [ -f "${d}SKILL.md" ] || continue
  name="$(basename "$d")"
  ln -sfn "${d%/}" "$CLAUDE_SKILLS_DIR/$name"
  echo "  ✓ $name"
done

# ── Global ~/.claude/CLAUDE.md ───────────────────────────────────────────────
#
# Claude Code loads ~/.claude/CLAUDE.md IN ADDITION to a repo's own CLAUDE.md,
# so this is where personal context goes that must survive ai-devex. A RoE repo's
# CLAUDE.md is regenerated wholesale by ai-devex/scripts/setup.sh (it concatenates
# ai-devex/context/ over anything already there), so appending to it loses the
# content on the next update.sh. This file ai-devex never touches.
#
# The content itself lives in this repo's context/ — git-tracked and pushable —
# and is spliced into a delimited block below. Anything OUTSIDE the block is
# hand-written and preserved verbatim across re-runs.

GLOBAL_CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"

# Files from context/ to splice into ~/.claude/CLAUDE.md, in order. Deliberately
# an explicit allowlist, not a glob: context/ also holds the Idea Wrangler's
# standing grounding (strategy/non-goals/roadmap) plus a README, none of which
# belong in every Claude Code session.
GLOBAL_CONTEXT_FILES=(
  team
)

DOTAI_BLOCK_START="<!-- DOTAI-GENERATED -->"
DOTAI_BLOCK_END="<!-- /DOTAI-GENERATED -->"

if [ ! -f "$GLOBAL_CLAUDE_MD" ]; then
  echo ""
  echo "→ Creating ~/.claude/CLAUDE.md (user-level global context)"
  cat > "$GLOBAL_CLAUDE_MD" << 'EOF'
# Global Claude Context

# Import context docs from your repo's CLAUDE.md.
# Each repo's CLAUDE.md should contain the context relevant to that codebase.
EOF
  echo "  ✓ ~/.claude/CLAUDE.md created"
fi

# Build the block body from the allowlisted context files.
DOTAI_BLOCK_BODY="$(mktemp)"
{
  echo "$DOTAI_BLOCK_START"
  echo ""
  echo "<!-- Generated by dotai/scripts/setup.sh from dotai/context/."
  echo "     Edit the source files and re-run; edits here are overwritten."
  echo "     Content outside this block is preserved. -->"
  for context_file in "${GLOBAL_CONTEXT_FILES[@]}"; do
    src="$DEVEX_DIR/context/${context_file}.md"
    if [ -f "$src" ]; then
      echo ""
      echo "---"
      echo ""
      cat "$src"
    else
      echo "  ⚠ context/${context_file}.md not found — skipped" >&2
    fi
  done
  echo ""
  echo "$DOTAI_BLOCK_END"
} > "$DOTAI_BLOCK_BODY"

echo ""
echo "→ Syncing personal context block into ~/.claude/CLAUDE.md"
if command -v python3 &>/dev/null; then
  python3 - "$GLOBAL_CLAUDE_MD" "$DOTAI_BLOCK_BODY" "$DOTAI_BLOCK_START" "$DOTAI_BLOCK_END" <<'SPLICEPY'
import sys

target, body_path, start, end = sys.argv[1:5]

with open(target) as f:
    current = f.read()
with open(body_path) as f:
    block = f.read().rstrip("\n")

if start in current and end in current:
    head, rest = current.split(start, 1)
    _, tail = rest.split(end, 1)
    updated = head + block + tail
    action = "refreshed"
elif start in current or end in current:
    # One delimiter without the other: a hand-edit truncated the block. Refuse
    # rather than guess where it ended and silently eat the file's real content.
    sys.exit("  ✗ ~/.claude/CLAUDE.md has a broken DOTAI-GENERATED block "
             "(one delimiter missing). Fix it by hand, then re-run.")
else:
    updated = current.rstrip("\n") + "\n\n" + block + "\n"
    action = "added"

if updated != current:
    with open(target, "w") as f:
        f.write(updated)
    print("  ✓ personal context block %s" % action)
else:
    print("  → personal context block already up to date")
SPLICEPY
else
  echo "  ⚠ python3 not found — skipped (block not synced)"
fi
rm -f "$DOTAI_BLOCK_BODY"

# ── Global ~/.claude/settings.json — ensure it exists ────────────────────────
#
# The permissions merge below json.load()s this file with no existence check,
# so it must exist by the time we get there. Nothing else is written here:
# statusLine is deliberately NOT configured. It previously installed
# `npx -y ccstatusline@latest`, which re-resolved over the network and spawned
# a process on EVERY statusline render; with no reaping init in the
# devcontainer (PID 1 is `sleep infinity`) those accumulated as zombies.

GLOBAL_SETTINGS="$CLAUDE_DIR/settings.json"

if [ ! -f "$GLOBAL_SETTINGS" ]; then
  echo ""
  echo "→ Creating ~/.claude/settings.json"
  printf '{}\n' > "$GLOBAL_SETTINGS"
  echo "  ✓ ~/.claude/settings.json created"
fi

# ── Repo CLAUDE.md ────────────────────────────────────────────────────────────

if [ ! -f "$REPO_DIR/CLAUDE.md" ]; then
  echo ""
  echo "→ No CLAUDE.md found in repo — copying template"
  cp "$DEVEX_DIR/templates/CLAUDE.md" "$REPO_DIR/CLAUDE.md"
  echo "  ✓ CLAUDE.md created from template (fill in the repo-specific sections)"
else
  echo ""
  echo "→ CLAUDE.md already exists in repo — leaving it unchanged"
fi

# ── ~/.claude/settings.json — merge permissions from template ────────────────

SETTINGS_TEMPLATE="$DEVEX_DIR/templates/settings.json"

echo ""
echo "→ Merging permissions into ~/.claude/settings.json"

if [ -f "$SETTINGS_TEMPLATE" ]; then
  python3 - "$GLOBAL_SETTINGS" "$SETTINGS_TEMPLATE" <<'PYEOF'
import json, sys

settings_path = sys.argv[1]
template_path = sys.argv[2]

with open(settings_path) as f:
    settings = json.load(f)

with open(template_path) as f:
    template = json.load(f)

# Merge permissions: union of allow/ask/deny lists, preserving existing entries.
# `ask` MUST be in this tuple. It was omitted until 2026-08-25, which silently
# dropped the whole prompt-me tier on every run — the template's rules were
# never installed and `deny` was doing all the gating on its own.
tpl_perms = template.get("permissions", {})
cur_perms = settings.get("permissions", {})

for key in ("allow", "ask", "deny"):
    existing = set(cur_perms.get(key, []))
    incoming = set(tpl_perms.get(key, []))
    merged = sorted(existing | incoming)
    if merged:
        cur_perms[key] = merged

if cur_perms:
    settings["permissions"] = cur_perms

with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")

print("  ✓ permissions merged into ~/.claude/settings.json")
PYEOF
else
  echo "  ⚠ No template found at $SETTINGS_TEMPLATE — skipping"
fi

# ── Claude Code CLI ───────────────────────────────────────────────────────────
# Personal setup — install the Claude Code CLI if it's missing so the plugin
# registration below (guarded by `command -v claude`) actually runs instead of
# silently skipping. This lives in dotai, not the shared devcontainer/ai-devex.
if ! command -v claude &>/dev/null; then
  if command -v npm &>/dev/null; then
    echo ""
    echo "→ Installing Claude Code CLI (npm -g @anthropic-ai/claude-code)"
    # --allow-scripts runs the package postinstall (install.cjs) that npm's
    # allow-scripts gating otherwise blocks.
    if npm install -g --allow-scripts=@anthropic-ai/claude-code @anthropic-ai/claude-code; then
      echo "  ✓ Claude Code installed: $(claude --version 2>/dev/null || echo 'check PATH')"
    else
      echo "  ⚠ Claude Code install failed — install manually: npm install -g @anthropic-ai/claude-code"
    fi
  else
    echo ""
    echo "⚠ npm not found — cannot install Claude Code CLI"
  fi
fi

# ── Linear personal token from 1Password (personal dotai) ──────────────────────
# Resolve my personal Linear API key from 1Password so BOTH the Linear CLI and
# the key-based `linear` MCP (registered below) come up authenticated without
# pasting keys. The key lives in the personal "Employee" vault, item "Linear",
# field "credential" — verified 2026-08-30 against `op item get`. All three parts
# were previously wrong (vault "Rock of Eye", item "Linear API Key", field
# "notesPlain", which is present on the item but EMPTY), so the resolution had
# never once succeeded. Override with LINEAR_OP_REF on a machine that differs.
# Gracefully skips if op can't resolve
# it, so a run never hard-fails.
#
# The account is whatever OP_ACCOUNT names, because the shorthand is per-machine:
# the RoE devcontainer sets OP_ACCOUNT=rockofeyesoftware, and hardcoding
# "my.1password.com" there made op fail with `found no accounts for filter` on
# every run — while the message below blamed a missing agent.sock, which sent a
# debugging session after the wrong thing entirely. Fall back to the old default
# only when OP_ACCOUNT is unset.
LINEAR_OP_ACCOUNT="${OP_ACCOUNT:-my.1password.com}"
LINEAR_OP_REF="${LINEAR_OP_REF:-op://Employee/Linear/credential}"
if [ -z "${LINEAR_ACCESS_TOKEN:-}" ] && command -v op &>/dev/null; then
  echo ""
  echo "→ Resolving Linear API key from 1Password ($LINEAR_OP_REF, account $LINEAR_OP_ACCOUNT)"
  _linear_err="$(mktemp)"
  if _linear_tok="$(op read --account "$LINEAR_OP_ACCOUNT" "$LINEAR_OP_REF" 2>"$_linear_err")" \
     && [ -n "$_linear_tok" ]; then
    export LINEAR_ACCESS_TOKEN="$_linear_tok"
    export LINEAR_API_KEY="${LINEAR_API_KEY:-$_linear_tok}"  # env name used by the CLI / skills
    unset _linear_tok
    echo "  ✓ Linear key resolved from 1Password"
  else
    # Print what op actually said. Guessing the cause here is how the account
    # mismatch above stayed hidden.
    echo "  ⚠ Could not resolve Linear key from 1Password — skipping. op said:"
    sed 's/^/      /' "$_linear_err" | head -3
    echo "      (check: op account list — the shorthand must match OP_ACCOUNT)"
  fi
  rm -f "$_linear_err"
fi

# Authenticate the Linear CLI with that key. --plaintext writes to ~/.config/linear
# (on the persisted volume, survives rebuilds); the headless container has no keyring.
if [ -n "${LINEAR_ACCESS_TOKEN:-}" ] && command -v linear &>/dev/null; then
  # `linear auth token` reads LINEAR_API_KEY from the ENVIRONMENT — which this
  # script exported ~15 lines above — so the old "already authenticated?" guard
  # ALWAYS passed and the login branch was unreachable. The CLI was therefore
  # never persistently authenticated by setup, and a rotated key never reached
  # ~/.config/linear/credentials.toml. Just write the key every run; login is
  # idempotent and this is what makes a rotation actually land.
  if linear auth login --plaintext --key "$LINEAR_ACCESS_TOKEN" &>/dev/null; then
    echo "  ✓ Linear CLI authenticated (key from 1Password)"
  else
    echo "  ⚠ Linear CLI login failed"
  fi
  # Prove it PERSISTED, with the env vars stripped — otherwise this reports the
  # environment back to itself, which is the bug above.
  if env -u LINEAR_API_KEY -u LINEAR_ACCESS_TOKEN linear auth token &>/dev/null; then
    echo "  ✓ Linear CLI auth persisted (survives a fresh shell)"
  else
    echo "  ⚠ Linear CLI auth did NOT persist — works only while the env var is set"
  fi
fi

# ── Claude Code Plugins ───────────────────────────────────────────────────────

# Resolve claude binary — may not be on PATH when running under sudo
CLAUDE_BIN=""
if command -v claude &>/dev/null; then
  CLAUDE_BIN="claude"
elif [ -x "$HOME/.local/bin/claude" ]; then
  CLAUDE_BIN="$HOME/.local/bin/claude"
elif [ -n "${SUDO_USER:-}" ]; then
  _sudo_home="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
  if [ -x "$_sudo_home/.local/bin/claude" ]; then
    CLAUDE_BIN="$_sudo_home/.local/bin/claude"
  fi
fi

if [ -n "$CLAUDE_BIN" ]; then
  echo ""
  echo "→ Registering Claude Code plugins (using $CLAUDE_BIN)"

  # Mask secret-looking env assignments in anything we print. `claude mcp add`
  # echoes the full command back on success — including `-e LINEAR_ACCESS_TOKEN=
  # lin_api_…` — which lands verbatim in any captured log or terminal scrollback.
  # That leaked a live Linear key on 2026-08-30.
  _mask_secrets() {
    sed -E 's/([A-Za-z_]*(TOKEN|KEY|SECRET|PASSWORD|CREDENTIAL)[A-Za-z_]*=)[^[:space:]]*/\1***/g'
  }

  # Helper: register an MCP server scoped to the user; skips if already present.
  # Never prints the subcommand's raw output — but DOES print it, masked, on
  # failure: a diagnostic that hides the real error is how three unrelated
  # 1Password failures stayed invisible behind one guessed cause (#17, #18).
  _mcp_add() {
    local name="$1"; shift
    if "$CLAUDE_BIN" mcp get "$name" &>/dev/null 2>&1; then
      echo "  → $name already registered — skipping"
    else
      local _out
      if _out="$("$CLAUDE_BIN" mcp add --scope user "$name" "$@" 2>&1)"; then
        echo "  ✓ $name"
      else
        echo "  ✗ $name — registration failed:"
        printf '%s\n' "$_out" | _mask_secrets | sed 's/^/      /' | head -5
      fi
    fi
  }

  # Helper: register a remote (HTTP) MCP server scoped to the user; skips if present.
  # Remote servers authenticate via OAuth rather than an env-var token — after
  # registration, run /mcp inside a Claude Code session to complete the browser flow.
  _mcp_add_http() {
    local name="$1"; local url="$2"
    if "$CLAUDE_BIN" mcp get "$name" &>/dev/null 2>&1; then
      echo "  → $name already registered — skipping"
    else
      "$CLAUDE_BIN" mcp add --transport http --scope user "$name" "$url" \
        && echo "  ✓ $name (remote — run /mcp to authenticate)" \
        || echo "  ✗ $name — registration failed"
    fi
  }

  # Superpowers — TDD, debugging, and collaboration workflow skills
  _mcp_add superpowers          -- npx -y superpowers-mcp

  # Context7 — pulls up-to-date library docs into context
  _mcp_add context7             -- npx -y @upstash/context7-mcp@latest

  # Code-reviewer — AI-powered code review via MCP
  _mcp_add code-reviewer        -- npx -y code-review-mcp

  # PR review toolkit — GraphQL-based GitHub PR review
  _mcp_add pr-review-toolkit    -- npx -y pr-review-mcp

  # Linear — OFFICIAL remote MCP (OAuth 2.1, dynamic client registration).
  # Deliberately NOT the key-based stdio server: that put a Personal API key in
  # ~/.claude.json in plaintext, made every client need the key distributed to
  # it, and turned a key rotation into a five-consumer sweep. OAuth needs no key
  # at all and authenticates each person as themselves.
  # A pre-existing STDIO `linear` entry is stale — drop it so the http one lands.
  if "$CLAUDE_BIN" mcp get linear 2>/dev/null | command grep -qi 'stdio'; then
    echo "  → removing the stale stdio linear registration"
    "$CLAUDE_BIN" mcp remove linear --scope user >/dev/null 2>&1 || true
  fi
  _mcp_add_http linear          https://mcp.linear.app/mcp

  # Notion — official remote MCP (OAuth). AI read/write over Notion pages,
  # databases, and search. After registration, run /mcp in a Claude Code session
  # to authorise and choose which pages/teamspaces to expose.
  _mcp_add_http notion          https://mcp.notion.com/mcp

  # Helper: register a plugin marketplace (idempotent) then install a plugin at
  # user scope. Marketplace + install state live in ~/.claude (settings.json
  # `extraKnownMarketplaces` + the plugins cache) and are shared with the VS Code
  # extension, so a plugin added here also shows up under `/plugins` there.
  _plugin_add() {
    local plugin="$1"; local marketplace="$2"; local repo="$3"
    if "$CLAUDE_BIN" plugin marketplace list 2>/dev/null | grep -q "$marketplace"; then
      :
    else
      "$CLAUDE_BIN" plugin marketplace add "$repo" &>/dev/null \
        && echo "  ✓ marketplace $marketplace ($repo)" \
        || echo "  ✗ marketplace $marketplace — add failed ($repo)"
    fi
    if "$CLAUDE_BIN" plugin list 2>/dev/null | grep -q "$plugin"; then
      echo "  → $plugin already installed — skipping"
    else
      "$CLAUDE_BIN" plugin install "$plugin@$marketplace" --scope user &>/dev/null \
        && echo "  ✓ $plugin" \
        || echo "  ✗ $plugin — install failed (run: $CLAUDE_BIN plugin install $plugin@$marketplace)"
    fi
  }

  # Impeccable — design fluency for frontend work: 1 skill, 23 `/impeccable`
  # commands (polish, audit, critique, typeset, distill, document …) + curated
  # anti-pattern ("slop") detection, and the portable DESIGN.md format we author
  # our design systems in. https://impeccable.style
  _plugin_add impeccable impeccable pbakaus/impeccable

  # Code-simplifier and Claude-md-management are other native plugins you can add
  # the same way once their marketplaces are published, e.g.:
  #   _plugin_add code-simplifier <marketplace> <owner/repo>

else
  echo ""
  echo "⚠ Claude Code not found — skipping plugin registration"
  echo "  Install Claude Code (~/.local/bin/claude) and re-run this script to register plugins"
fi

# ── Cursor / Windsurf ────────────────────────────────────────────────────────

CURSOR_RULES="$REPO_DIR/.cursorrules"
WINDSURF_RULES="$REPO_DIR/.windsurfrules"

if [ ! -f "$CURSOR_RULES" ] && command -v cursor &>/dev/null; then
  echo ""
  echo "→ Cursor detected — symlinking context into .cursorrules"
  ln -sf "$DEVEX_DIR/templates/CLAUDE.md" "$CURSOR_RULES"
  echo "  ✓ .cursorrules linked (points to CLAUDE.md template)"
fi

if [ ! -f "$WINDSURF_RULES" ] && command -v windsurf &>/dev/null; then
  echo ""
  echo "→ Windsurf detected — symlinking context into .windsurfrules"
  ln -sf "$DEVEX_DIR/templates/AGENT.md" "$WINDSURF_RULES"
  echo "  ✓ .windsurfrules linked (points to AGENT.md template)"
fi

# ── Personal Firstmate launcher ───────────────────────────────────────────────
# A PATH command in ~/.local/bin (owned by this user, same pattern as the
# Treehouse wrapper). Not a bash alias: Herdr panes and non-interactive shells
# do not load aliases. Team local-dev-env is untouched.

FM_LAUNCHER="$DEVEX_DIR/scripts/firstmate-local.sh"
if [ -x "$FM_LAUNCHER" ]; then
  echo ""
  echo "→ Installing personal fm launcher"
  mkdir -p "$HOME/.local/bin"
  ln -sfn "$FM_LAUNCHER" "$HOME/.local/bin/fm"
  echo "  ✓ fm → $FM_LAUNCHER"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "✅ Setup complete."
echo ""
echo "Next steps:"
if [ -f "$REPO_DIR/CLAUDE.md" ] && grep -q "\[REPO NAME\]" "$REPO_DIR/CLAUDE.md" 2>/dev/null; then
  echo "  1. Open CLAUDE.md and fill in the repo-specific sections (search for [REPO NAME])"
fi
echo "  • Slash commands in Claude Code: /pr-summary, /review, /test, /adr"
echo "  • MCP plugins registered:        superpowers, context7, code-reviewer, pr-review-toolkit, linear, notion"
echo "  • Marketplace plugins:           configure a marketplace to install code-simplifier + claude-md-management"
echo "  • Start a session:               claude"
echo ""
