// Shared compose helpers: recipient allowlist enforcement, rendering, drafts.

import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { DRAFTS_DIR, allowlist, settings, fail } from './config.mjs';

export function splitAddrs(s) {
  if (!s) return [];
  return String(s).split(',').map((x) => x.trim()).filter(Boolean);
}

// Hard allowlist gate. Returns the lowercased recipient list or exits.
export function enforceAllowlist(recipients) {
  const allow = allowlist();
  if (!allow.length) {
    fail('Recipient allowlist is EMPTY — refusing to send to anyone.\n' +
      'Add André + the Founder to config/allowlist.json first.');
  }
  const blocked = recipients.filter((r) => !allow.includes(r.toLowerCase()));
  if (blocked.length) {
    fail(`Recipient(s) not on the allowlist: ${blocked.join(', ')}\n` +
      `Allowed: ${allow.join(', ')}\n` +
      `This guardrail is deliberate — the agent may only email the allowlist.`);
  }
  return recipients;
}

export function footer() {
  return settings().provenance_footer ||
    '\n\n—\nSent by André’s local-dev AI agent. This message was generated by an AI agent on his behalf.';
}

export function renderPreview({ from, to, cc, subject, body, redactCount }) {
  const lines = [
    '┌─ EMAIL DRAFT ' + '─'.repeat(50),
    `│ From:    ${from || '(resolved at send)'}`,
    `│ To:      ${to.join(', ')}`,
    ...(cc && cc.length ? [`│ Cc:      ${cc.join(', ')}`] : []),
    `│ Subject: ${subject}`,
    redactCount ? `│ ⚠ Redactions applied: ${redactCount}` : '│ Redactions: none',
    '├' + '─'.repeat(64),
    ...body.split('\n').map((l) => `│ ${l}`),
    '└' + '─'.repeat(64),
  ];
  return lines.join('\n');
}

export function writeDraft(draft) {
  mkdirSync(DRAFTS_DIR, { recursive: true });
  const id = draft.id || `${new Date().toISOString().replace(/[:.]/g, '-')}-${randomUUID().slice(0, 8)}`;
  const path = join(DRAFTS_DIR, `${id}.json`);
  writeFileSync(path, JSON.stringify({ ...draft, id }, null, 2));
  return { id, path };
}

export function readDraft(id) {
  const path = join(DRAFTS_DIR, `${id}.json`);
  if (!existsSync(path)) fail(`Draft not found: ${id} (looked in ${DRAFTS_DIR})`);
  return JSON.parse(readFileSync(path, 'utf8'));
}
